#! ruby
require 'test/unit'
require 'clipboard_manager/version'

class TestVersion < Test::Unit::TestCase
  VERSION = '1.1.1'
  def test_version
    assert_nothing_raised() do
      assert_equal VERSION, ClipboardManager::VERSION
      assert_equal VERSION, File.read('./data/VERSION').strip
      assert( system "grep version clipboard_manager.gemspec | grep = | grep #{VERSION}" )
    end
  end
end
