#!/usr/bin/env ruby

RUBY = 'ruby -I ./lib'
LOG = './test/errors.log'

def fn(name)
  "./test/tc_#{name}"
end

def tc(name)
  system "#{RUBY} #{fn(name)} > #{LOG}"
end

if tc('version')    and
   tc('config')
  puts 'All tests passed!'
  File.unlink LOG
else
  puts "There were errors.  See #{LOG}"
  exit 1
end
