---
:Help: |
  Usage: gtk3app clipboardmanager [options]
  Options:
    --ask      Ask for confirmation.
    --running  Start in active mode.
  Default for options is true,
  use no-ask and no-running for false.
:StatusTimeOut: 3
:Sleep: 750
:MaxHistory: 13
:MaxString: 60
:QrcTimeOut: 3
:QrcCommand: zbarcam --nodisplay --raw --prescale=800x800
:IsPwd: |-
  \A
    (?!\w+:\/\/)          # not like url
    (?!\/[a-z]+\/[a-z])   # not like linux path
    (?![a-z]+\/[a-z]+\/)  # not like relative path
    (?=.*\d)              # at least on diget
    (?=.*[a-z])           # at least one lower case letter
    (?=.*[A-Z])           # at least one upper case letter
    (?=.*[^\w\s])         # at least one special character
    .{4,43}$              # 4 to 43 in length
  \Z
:Working: "/home/fox/.local/share/gtk3app/clipboardmanager/working.png"
:Ok: "/home/fox/.local/share/gtk3app/clipboardmanager/ok.png"
:Nope: "/home/fox/.local/share/gtk3app/clipboardmanager/nope.png"
:Ready: "/home/fox/.local/share/gtk3app/clipboardmanager/ready.png"
:Off: "/home/fox/.local/share/gtk3app/clipboardmanager/off.png"
:thing:
  :HelpFile: https://github.com/carlosjhr64/clipboard_manager
  :Logo: "/home/fox/.local/share/gtk3app/clipboardmanager/logo.png"
  :about_dialog:
    :set_program_name: Clipboard Manager
    :set_version: 1.0.0
    :set_copyright: "(c) 2014 CarlosJHR64"
    :set_comments: 'A Ruby Gtk3App Clipboard Manager '
    :set_website: https://github.com/carlosjhr64/clipboard_manager
    :set_website_label: See it at GitHub!
  :DO_TOGGLE:
  - Toggle On/Off
  :do_toggle!:
  - :DO_TOGGLE
  - activate
  :DO_HISTORY:
  - History
  :do_history!:
  - :DO_HISTORY
  - activate
  :DO_QRCODE:
  - QR-Code
  :do_qrcode!:
  - :DO_QRCODE
  - activate
  :window:
    :set_title: Clipboard Manager
    :set_window_position: :center
  :VBOX:
  - :vertical
  :vbox: &1 {}
  :vbox!:
  - :VBOX
  - :vbox
  :ASK:
  - Ask For Confirmation
  :ask: *1
  :ask!:
  - :ASK
  - :ask
  :RUNNING:
  - On/Off
  :running: *1
  :running!:
  - :RUNNING
  - :running
  :TASKS:
  - 'Tasks:'
  :tasks: *1
  :tasks!:
  - :TASKS
  - :tasks
  :HISTORY_BUTTON:
  - :label: History
  :history_button: *1
  :history_button!:
  - :HISTORY_BUTTON
  - :history_button
  :HISTORY_DIALOG: &2 []
  :history_dialog:
    :set_window_position: :center
  :history_dialog!:
  - :HISTORY_DIALOG
  - :history_dialog
  :HISTORY_COMBO: *2
  :history_combo: *1
  :history_combo!:
  - :HISTORY_COMBO
  - :history_combo
  :QRCODE_BUTTON:
  - :label: QR-Code
  :qrcode_button: *1
  :qrcode_button!:
  - :QRCODE_BUTTON
  - :qrcode_button
  :QUESTION_DIALOG: *2
  :question_dialog:
    :set_window_position: :center
    :set_keep_above: true
  :question_dialog!:
  - :question_dialog
  - :QUESTION_DIALOG
:tasks:
  :mplayer:
  - "(https?://www\\.youtube\\.com/watch\\?v=[\\w\\-]+)"
  - :bashit
  - wget --quiet -O - $(youtube-dl -f 5/36/17/18 -g '$1') | mplayer -really-quiet
    -cache 8192 -cache-min 1 -
  :firefox:
  - "^https?://www.amazon.com/"
  - :firefox
  :espeak:
  - ".{80,}"
  - :espeak
